[package]
name = "dokrust"
version = "0.1.0"
authors = ["lishpr <https://github.com/lishpr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
nix = "0.19.1"
simple-error = "0.2.2"
ip-command = "0.1.0"